package com.lsl.manager.mapper;

import com.lsl.manager.model.Family;
import com.lsl.manager.model.FamilyExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface FamilyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table familyTb
     *
     * @mbg.generated Fri Jan 17 22:15:00 GMT+08:00 2020
     */
    long countByExample(FamilyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table familyTb
     *
     * @mbg.generated Fri Jan 17 22:15:00 GMT+08:00 2020
     */
    int deleteByExample(FamilyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table familyTb
     *
     * @mbg.generated Fri Jan 17 22:15:00 GMT+08:00 2020
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table familyTb
     *
     * @mbg.generated Fri Jan 17 22:15:00 GMT+08:00 2020
     */
    int insert(Family record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table familyTb
     *
     * @mbg.generated Fri Jan 17 22:15:00 GMT+08:00 2020
     */
    int insertSelective(Family record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table familyTb
     *
     * @mbg.generated Fri Jan 17 22:15:00 GMT+08:00 2020
     */
    List<Family> selectByExampleWithRowbounds(FamilyExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table familyTb
     *
     * @mbg.generated Fri Jan 17 22:15:00 GMT+08:00 2020
     */
    List<Family> selectByExample(FamilyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table familyTb
     *
     * @mbg.generated Fri Jan 17 22:15:00 GMT+08:00 2020
     */
    Family selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table familyTb
     *
     * @mbg.generated Fri Jan 17 22:15:00 GMT+08:00 2020
     */
    int updateByExampleSelective(@Param("record") Family record, @Param("example") FamilyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table familyTb
     *
     * @mbg.generated Fri Jan 17 22:15:00 GMT+08:00 2020
     */
    int updateByExample(@Param("record") Family record, @Param("example") FamilyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table familyTb
     *
     * @mbg.generated Fri Jan 17 22:15:00 GMT+08:00 2020
     */
    int updateByPrimaryKeySelective(Family record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table familyTb
     *
     * @mbg.generated Fri Jan 17 22:15:00 GMT+08:00 2020
     */
    int updateByPrimaryKey(Family record);
}