package com.lsl.manager.mapper;

import com.lsl.manager.model.KaoQin;
import com.lsl.manager.model.KaoQinExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface KaoQinMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kaoqinTb
     *
     * @mbg.generated Fri Jan 17 22:18:01 GMT+08:00 2020
     */
    long countByExample(KaoQinExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kaoqinTb
     *
     * @mbg.generated Fri Jan 17 22:18:01 GMT+08:00 2020
     */
    int deleteByExample(KaoQinExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kaoqinTb
     *
     * @mbg.generated Fri Jan 17 22:18:01 GMT+08:00 2020
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kaoqinTb
     *
     * @mbg.generated Fri Jan 17 22:18:01 GMT+08:00 2020
     */
    int insert(KaoQin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kaoqinTb
     *
     * @mbg.generated Fri Jan 17 22:18:01 GMT+08:00 2020
     */
    int insertSelective(KaoQin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kaoqinTb
     *
     * @mbg.generated Fri Jan 17 22:18:01 GMT+08:00 2020
     */
    List<KaoQin> selectByExampleWithRowbounds(KaoQinExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kaoqinTb
     *
     * @mbg.generated Fri Jan 17 22:18:01 GMT+08:00 2020
     */
    List<KaoQin> selectByExample(KaoQinExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kaoqinTb
     *
     * @mbg.generated Fri Jan 17 22:18:01 GMT+08:00 2020
     */
    KaoQin selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kaoqinTb
     *
     * @mbg.generated Fri Jan 17 22:18:01 GMT+08:00 2020
     */
    int updateByExampleSelective(@Param("record") KaoQin record, @Param("example") KaoQinExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kaoqinTb
     *
     * @mbg.generated Fri Jan 17 22:18:01 GMT+08:00 2020
     */
    int updateByExample(@Param("record") KaoQin record, @Param("example") KaoQinExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kaoqinTb
     *
     * @mbg.generated Fri Jan 17 22:18:01 GMT+08:00 2020
     */
    int updateByPrimaryKeySelective(KaoQin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kaoqinTb
     *
     * @mbg.generated Fri Jan 17 22:18:01 GMT+08:00 2020
     */
    int updateByPrimaryKey(KaoQin record);
}