package com.lsl.manager.mapper;

import com.lsl.manager.model.User;
import com.lsl.manager.model.UserExample;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;
@Mapper
public interface UserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userTb
     *
     * @mbg.generated Fri Jan 17 22:18:01 GMT+08:00 2020
     */
    long countByExample(UserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userTb
     *
     * @mbg.generated Fri Jan 17 22:18:01 GMT+08:00 2020
     */
    int deleteByExample(UserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userTb
     *
     * @mbg.generated Fri Jan 17 22:18:01 GMT+08:00 2020
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userTb
     *
     * @mbg.generated Fri Jan 17 22:18:01 GMT+08:00 2020
     */
    int insert(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userTb
     *
     * @mbg.generated Fri Jan 17 22:18:01 GMT+08:00 2020
     */
    int insertSelective(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userTb
     *
     * @mbg.generated Fri Jan 17 22:18:01 GMT+08:00 2020
     */
    List<User> selectByExampleWithRowbounds(UserExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userTb
     *
     * @mbg.generated Fri Jan 17 22:18:01 GMT+08:00 2020
     */
    List<User> selectByExample(UserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userTb
     *
     * @mbg.generated Fri Jan 17 22:18:01 GMT+08:00 2020
     */
    User selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userTb
     *
     * @mbg.generated Fri Jan 17 22:18:01 GMT+08:00 2020
     */
    int updateByExampleSelective(@Param("record") User record, @Param("example") UserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userTb
     *
     * @mbg.generated Fri Jan 17 22:18:01 GMT+08:00 2020
     */
    int updateByExample(@Param("record") User record, @Param("example") UserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userTb
     *
     * @mbg.generated Fri Jan 17 22:18:01 GMT+08:00 2020
     */
    int updateByPrimaryKeySelective(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userTb
     *
     * @mbg.generated Fri Jan 17 22:18:01 GMT+08:00 2020
     */
    int updateByPrimaryKey(User record);
}